import filterIcon from 'assets/filter.svg';

export const ColumnsData = [
  {
    key: 'date',
    name: 'Date',
    alignText: 'center',
    width: '150px',
    icon: filterIcon,
  },
  {
    key: 'id',
    name: 'ID',
    alignText: 'center',
    width: '150px',
    icon: filterIcon,
  },
  {
    key: 'name',
    name: 'Name',
    alignText: 'center',
    width: '150px',
    icon: filterIcon,
  },
  {
    key: 'checkin',
    name: 'Checkin',
    alignText: 'center',
    width: '150px',
    icon: filterIcon,
  },
  {
    key: 'checkout',
    name: 'Checkout',
    alignText: 'center',
    width: '250px',
    icon: filterIcon,
  },
  {
    key: 'hours',
    name: 'Hours',
    alignText: 'center',
    width: '250px',
    icon: filterIcon,
  },
  {
    key: 'type',
    name: 'Type',
    alignText: 'center',
    width: '250px',
    icon: filterIcon,
  },
  {
    key: 'status',
    name: 'Status',
    alignText: 'center',
    width: '250px',
    icon: filterIcon,
  },
  {
    key: 'tags',
    name: 'Tags',
    alignText: 'center',
    width: '250px',
    icon: filterIcon,
  },
  { key: 'actions', name: 'Actions', alignText: 'center', width: '200px' },
];

export const Colors: any = {
  Present: '#57B894',
  Absent: '#DB4141',
  HalfDay: '#F7AC08',
  ShortLeave: '#FF9F65',
};

export const RowsData = [
  {
    date: '12/10/2022',
    id: 'SRX001',
    name: 'Jack Grow',
    checkin: '10:00 AM',
    checkout: '07:00 PM',
    hours: '7.25',
    type: 'Work day',
    status: 'Present',
    tags: 'short leave',
  },
  {
    date: '12/10/2022',
    id: 'SRX001',
    name: 'Jack Sparrow',
    checkin: '12:00 AM',
    checkout: '07:00 PM',
    hours: '7.25',
    type: 'Work day',
    status: 'Absent',
    tags: 'short leave',
  },
  {
    date: '12/10/2022',
    id: 'SRX001',
    name: 'White',
    checkin: '11:00 AM',
    checkout: '07:00 PM',
    hours: '7.25',
    type: 'Work day',
    status: 'HalfDay',
    tags: 'short leave',
  },
  {
    date: '12/10/2022',
    id: 'SRX001',
    name: 'White',
    checkin: '12:00 AM',
    checkout: '07:00 PM',
    hours: '7.25',
    type: 'Work day',
    status: 'HalfDay',
    tags: 'short leave',
  },
  {
    date: '12/10/2022',
    id: 'SRX001',
    name: 'White',
    checkin: '12:00 AM',
    checkout: '07:00 PM',
    hours: '7.25',
    type: 'Work day',
    status: 'HalfDay',
    tags: 'short leave',
  },
  {
    date: '12/10/2022',
    id: 'SRX001',
    name: 'White',
    checkin: '11:00 AM',
    checkout: '07:00 PM',
    hours: '7.25',
    type: 'Work day',
    status: 'HalfDay',
    tags: 'short leave',
  },
  {
    date: '12/10/2022',
    id: 'SRX001',
    name: 'White',
    checkin: '12:00 AM',
    checkout: '07:00 PM',
    hours: '7.25',
    type: 'Work day',
    status: 'HalfDay',
    tags: 'short leave',
  },
];
