import girl from 'assets/employee-page/Mask Group 3.svg';
import { Employee } from 'interfaces/employee';

export interface EmployeeFilterData {
  name: string;
  employeeId: string;
  account: string;
}

export const employees: Employee[] = [
  {
    name: 'Sara Logan sakjhkd askjdsan ajsds ajdka ',
    id: 'SPX001',
    img: girl,
    designation: 'Web development sakjdlkd sadsa sajdsa sjdsafa',
    email: 'Info32@gmail.com',
    phone: '0300-4358105',
    employeeId: 'asdsadsadd',
    status: '',
    userName: '',
  },
  {
    name: 'Sara Logan alkdjasd askdsal aslkns a',
    id: 'SPX002',
    img: girl,
    designation: 'Web development',
    email: 'Info32@gmail.com',
    phone: '0300-4358105',
    employeeId: 'asdsd;okasf adsd',
    status: '',
    userName: '',
  },
  {
    name: 'Sara Logan',
    id: 'SPX003',
    img: girl,
    designation: 'Web development',
    email: 'Info32@gmail.com',
    phone: '0300-4358105',
    employeeId: 'saosdada',
    status: '',
    userName: '',
  },
  {
    name: 'Sara Logan',
    id: 'SPX004',
    img: girl,
    designation: 'Web development',
    email: 'Info32@gmail.com',
    phone: '0300-4358105',
    employeeId: '',
    status: '',
    userName: '',
  },
  {
    name: 'Sara Logan',
    id: 'SPX004',
    img: girl,
    designation: 'Web development',
    email: 'Info32@gmail.com',
    phone: '0300-4358105',
    employeeId: '',
    status: '',
    userName: '',
  },
  {
    name: 'Sara Logan',
    id: 'SPX004',
    img: girl,
    designation: 'Web development',
    email: 'Info32@gmail.com',
    phone: '0300-4358105',
    employeeId: '',
    status: '',
    userName: '',
  },
  {
    name: 'Sara Logan',
    id: 'SPX004',
    img: girl,
    designation: 'Web development',
    email: 'Info32@gmail.com',
    phone: '0300-4358105',
    employeeId: '',
    status: '',
    userName: '',
  },
  {
    name: 'Sara Logan',
    id: 'SPX004',
    img: girl,
    designation: 'Web development',
    email: 'Info32@gmail.com',
    phone: '0300-4358105',
    employeeId: '',
    status: '',
    userName: '',
  },
  {
    name: 'Sara Logan',
    id: 'SPX004',
    img: girl,
    designation: 'Web development',
    email: 'Info32@gmail.com',
    phone: '0300-4358105',
    employeeId: '',
    status: '',
    userName: '',
  },
];
