export const ColumnsData = [
  {
    key: 'quota',
    name: 'Quota',
    alignText: 'center',
    width: '60px',
  },
  {
    key: 'effectiveDate',
    name: 'Effective Date',
    alignText: 'center',
    width: '150px',
  },
  {
    key: 'start',
    name: 'Start',
    alignText: 'center',
    width: '100px',
  },
  {
    key: 'end',
    name: 'End',
    alignText: 'center',
    width: '100px',
  },
  {
    key: 'sick',
    name: 'Sick',
    alignText: 'center',
    width: '60px',
  },
  {
    key: 'casual',
    name: 'Casual',
    alignText: 'center',
    width: '60px',
  },
  {
    key: 'annual',
    name: 'Annual',
    alignText: 'center',
    width: '60px',
  },
  {
    key: 'action',
    name: 'Action',
    alignText: 'center',
    width: '200px',
  },
]

export const RowsData = [
  {
    quota: 'a',
    effectiveDate: 'a',
    start: 'a',
    end: 'v',
    sick: 'sa',
    casual: 'as',
    annual: 'qw',
    action: 'qw',
  },
  {
    quota: 'a',
    effectiveDate: 'a',
    start: 'a',
    end: 'v',
    sick: 'sa',
    casual: 'as',
    annual: 'qw',
    action: 'qw',
  },
  {
    quota: 'a',
    effectiveDate: 'a',
    start: 'a',
    end: 'v',
    sick: 'sa',
    casual: 'as',
    annual: 'qw',
    action: 'qw',
  },
  {
    quota: 'a',
    effectiveDate: 'a',
    start: 'a',
    end: 'v',
    sick: 'sa',
    casual: 'as',
    annual: 'qw',
    action: 'qw',
  },
  {
    quota: 'a',
    effectiveDate: 'a',
    start: 'a',
    end: 'v',
    sick: 'sa',
    casual: 'as',
    annual: 'qw',
    action: 'qw',
  },
  {
    quota: 'a',
    effectiveDate: 'a',
    start: 'a',
    end: 'v',
    sick: 'sa',
    casual: 'as',
    annual: 'qw',
    action: 'qw',
  },
]

export const ColumnsData1 = [
  {
    key: 'effectiveDate',
    name: 'EffectiveForm',
    alignText: 'center',
    width: '150px',
  },
  {
    key: 'start',
    name: 'Effective To',
    alignText: 'center',
    width: '150px',
  },
  {
    key: 'start',
    name: 'Start',
    alignText: 'center',
    width: '150px',
  },
  {
    key: 'end',
    name: 'End',
    alignText: 'center',
    width: '150px',
  },
  {
    key: 'sick',
    name: 'Sick',
    alignText: 'center',
    width: '100px',
  },
  {
    key: 'casual',
    name: 'Casual',
    alignText: 'center',
    width: '100px',
  },
  {
    key: 'annual',
    name: 'Annual',
    alignText: 'center',
    width: '100px',
  },
]
